export const DISCORD_CUSTOM_ID_MAX_LENGTH = 100
export const DISCORD_BUTTON_LABEL_MAX_LENGTH = 80
export const DISCORD_SELECT_LABEL_MAX_LENGTH = 100
export const DISCORD_EMBED_TITLE_MAX_LENGTH = 256
export const DISCORD_EMBED_FIELD_NAME_MAX_LENGTH = 256
export const DISCORD_EMBED_FIELD_VALUE_MAX_LENGTH = 1024
export const DISCORD_EMBED_MAX_FIELDS = 25
export const DISCORD_EMBED_TOTAL_MAX_LENGTH = 6000

export const PINNED_BUTTON_LIMIT = 20
export const BUTTONS_PER_ROW = 5
export const GROUP_SELECT_VISIBLE_LIMIT = 24
export const PANEL_ACTIONS_PER_PAGE = 20
export const GROUP_BROWSER_PAGE_SIZE = 24
export const PALETTE_SOFT_CAP = 128

export const GROUP_SELECT_MORE_VALUE = '__more__'
export const SAFE_PROJECTION_ID_PATTERN = /^[a-z0-9]+$/
export const DISCORD_CHANNEL_ID_PATTERN = /^[0-9]+$/
