name: CI/CD Pipeline to AWS Lightsail

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # =================================================
  # 1) Build & Test (Docker Compose でアプリをテスト)
  # =================================================
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose plugin
        run: |
          sudo apt-get update && sudo apt-get install -y curl

          # 1) 既にインストールされている docker-compose を削除（衝突を避ける）
          sudo apt-get remove -y docker-compose || true

          # 2) Compose v2 の最新リリースを指定
          #   例: v2.15.1 の場合（定期的に更新してください）
          COMPOSE_VERSION="v2.15.1"

          # 3) バイナリをダウンロード & 配置
          sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose

          # 4) 実行権限付与
          sudo chmod +x /usr/local/bin/docker-compose

          # 5) バージョン確認
          docker-compose version

          # sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Docker Compose Build & Test
        run: |
          docker compose up -d --build
          # ここでテスト実行(例: appサービスにnpm testがあると想定)
          docker compose exec app npm install
          docker compose exec app npm test
          docker compose down


  # =================================================
  # 3) AWS Lightsail へデプロイ
  #    push-image が成功したら実行
  # =================================================
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Deploy to Lightsail
        run: |
          # Lightsail インスタンスの Public IP or ドメイン名
          SSH_HOST=${{ secrets.IPADRESS}}
          SSH_USER="ubuntu"

          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'ENDSSH'
            cd /workspace

            # 最新のイメージをpullしてコンテナを再起動
            docker compose pull
            docker compose up -d
          ENDSSH