name: Install Docker Compose
on:
  push:
    branches:
      - main
      - develop

jobs:
  install-docker-compose:
    name: Install Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install -y curl

          # 1) 既にインストールされている docker-compose を削除（衝突を避ける）
          sudo apt-get remove -y docker-compose || true

          # 2) Compose v2 の最新リリースを指定
          #   例: v2.15.1 の場合（定期的に更新してください）
          COMPOSE_VERSION="v2.15.1"

          # 3) バイナリをダウンロード & 配置
          sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose

          # 4) 実行権限付与
          sudo chmod +x /usr/local/bin/docker-compose

          # 5) バージョン確認
          docker-compose version