name: hoge

on:
  push:
    branches:
      - main
      - develop

jobs:
  hoge:
    name: Run hoge
    runs-on: ubuntu-latest
    steps:
      - name: echo hoge
        run: echo hoge
